-- Import 500+ German hospitals
-- Target: Scale from 115 to 600+ hospitals
-- Sources: Helios, Asklepios, Sana, Rhön, Catholic hospitals, municipal hospitals

INSERT INTO hospitals (name, type, plz, city, bundesland, website, beds_count, source, is_active, verified)
VALUES
  -- Helios Hospitals (Germany's largest private operator - 89 hospitals)
  ('Helios Klinikum Aue', 'Klinikum', '08280', 'Aue', 'Sachsen', 'https://www.helios-gesundheit.de/kliniken/aue', 450, ARRAY['manual'], true, true),
  ('Helios Klinikum Krefeld', 'Klinikum', '47805', 'Krefeld', 'Nordrhein-Westfalen', 'https://www.helios-gesundheit.de/kliniken/krefeld', 850, ARRAY['manual'], true, true),
  ('Helios Klinikum Emil von Behring Berlin', 'Klinikum', '14165', 'Berlin', 'Berlin', 'https://www.helios-gesundheit.de/kliniken/berlin-zehlendorf', 420, ARRAY['manual'], true, true),
  ('Helios Klinikum Pforzheim', 'Klinikum', '75175', 'Pforzheim', 'Baden-Württemberg', 'https://www.helios-gesundheit.de/kliniken/pforzheim', 550, ARRAY['manual'], true, true),
  ('Helios Klinikum Hildesheim', 'Klinikum', '31135', 'Hildesheim', 'Niedersachsen', 'https://www.helios-gesundheit.de/kliniken/hildesheim', 680, ARRAY['manual'], true, true),
  ('Helios Klinikum Schwelm', 'Klinikum', '58332', 'Schwelm', 'Nordrhein-Westfalen', 'https://www.helios-gesundheit.de/kliniken/schwelm', 400, ARRAY['manual'], true, true),
  ('Helios Klinikum Gotha', 'Klinikum', '99867', 'Gotha', 'Thüringen', 'https://www.helios-gesundheit.de/kliniken/gotha', 380, ARRAY['manual'], true, true),
  ('Helios Klinikum Meiningen', 'Klinikum', '98617', 'Meiningen', 'Thüringen', 'https://www.helios-gesundheit.de/kliniken/meiningen', 460, ARRAY['manual'], true, true),
  ('Helios Klinikum Sangerhausen', 'Klinikum', '06526', 'Sangerhausen', 'Sachsen-Anhalt', 'https://www.helios-gesundheit.de/kliniken/sangerhausen', 320, ARRAY['manual'], true, true),
  ('Helios Klinikum Schleswig', 'Klinikum', '24837', 'Schleswig', 'Schleswig-Holstein', 'https://www.helios-gesundheit.de/kliniken/schleswig', 440, ARRAY['manual'], true, true),
  ('Helios Klinikum Gifhorn', 'Klinikum', '38518', 'Gifhorn', 'Niedersachsen', 'https://www.helios-gesundheit.de/kliniken/gifhorn', 380, ARRAY['manual'], true, true),
  ('Helios Klinikum Uelzen', 'Klinikum', '29525', 'Uelzen', 'Niedersachsen', 'https://www.helios-gesundheit.de/kliniken/uelzen', 340, ARRAY['manual'], true, true),
  ('Helios Klinikum Lengerich', 'Klinikum', '49525', 'Lengerich', 'Nordrhein-Westfalen', 'https://www.helios-gesundheit.de/kliniken/lengerich', 280, ARRAY['manual'], true, true),
  ('Helios Klinikum Bad Saarow', 'Klinikum', '15526', 'Bad Saarow', 'Brandenburg', 'https://www.helios-gesundheit.de/kliniken/bad-saarow', 520, ARRAY['manual'], true, true),
  ('Helios Klinikum Niederberg Velbert', 'Klinikum', '42551', 'Velbert', 'Nordrhein-Westfalen', 'https://www.helios-gesundheit.de/kliniken/niederberg', 450, ARRAY['manual'], true, true),
  ('Helios St. Johannes Klinik Duisburg', 'Klinikum', '47166', 'Duisburg', 'Nordrhein-Westfalen', 'https://www.helios-gesundheit.de/kliniken/duisburg-johannesklinik', 380, ARRAY['manual'], true, true),
  ('Helios Klinik Rottweil', 'Klinikum', '78628', 'Rottweil', 'Baden-Württemberg', 'https://www.helios-gesundheit.de/kliniken/rottweil', 300, ARRAY['manual'], true, true),
  ('Helios Klinikum Pirna', 'Klinikum', '01796', 'Pirna', 'Sachsen', 'https://www.helios-gesundheit.de/kliniken/pirna', 420, ARRAY['manual'], true, true),

  -- Ask lepios Hospitals (38 hospitals)
  ('Asklepios Klinik St. Georg Hamburg', 'Krankenhaus', '20099', 'Hamburg', 'Hamburg', 'https://www.asklepios.com/hamburg/stgeorg', 850, ARRAY['manual'], true, true),
  ('Asklepios Klinik Wandsbek Hamburg', 'Krankenhaus', '22043', 'Hamburg', 'Hamburg', 'https://www.asklepios.com/hamburg/wandsbek', 650, ARRAY['manual'], true, true),
  ('Asklepios Klinik Harburg', 'Krankenhaus', '21075', 'Hamburg', 'Hamburg', 'https://www.asklepios.com/hamburg/harburg', 550, ARRAY['manual'], true, true),
  ('Asklepios Paulinen Klinik Wiesbaden', 'Klinikum', '65197', 'Wiesbaden', 'Hessen', 'https://www.asklepios.com/wiesbaden', 650, ARRAY['manual'], true, true),
  ('Asklepios Klinik Lich', 'Klinikum', '35423', 'Lich', 'Hessen', 'https://www.asklepios.com/lich', 420, ARRAY['manual'], true, true),
  ('Asklepios Kliniken Schildautal Seesen', 'Klinikum', '38723', 'Seesen', 'Niedersachsen', 'https://www.asklepios.com/seesen', 340, ARRAY['manual'], true, true),
  ('Asklepios Harzkliniken Goslar', 'Klinikum', '38642', 'Goslar', 'Niedersachsen', 'https://www.asklepios.com/goslar', 580, ARRAY['manual'], true, true),
  ('Asklepios Fachkliniken München-Gauting', 'Klinikum', '82131', 'Gauting', 'Bayern', 'https://www.asklepios.com/gauting', 420, ARRAY['manual'], true, true),
  ('Asklepios Klinik Birkenwerder', 'Klinikum', '16547', 'Birkenwerder', 'Brandenburg', 'https://www.asklepios.com/birkenwerder', 180, ARRAY['manual'], true, true),
  ('Asklepios Klinik Lindau', 'Klinikum', '88131', 'Lindau', 'Bayern', 'https://www.asklepios.com/lindau', 320, ARRAY['manual'], true, true),
  ('Asklepios Südpfalzkliniken', 'Klinikum', '76726', 'Germersheim', 'Rheinland-Pfalz', 'https://www.asklepios.com/germersheim', 450, ARRAY['manual'], true, true),
  ('Asklepios Klinik Langen', 'Klinikum', '63225', 'Langen', 'Hessen', 'https://www.asklepios.com/langen', 380, ARRAY['manual'], true, true),
  ('Asklepios Klinik Burglengenfeld', 'Klinikum', '93133', 'Burglengenfeld', 'Bayern', 'https://www.asklepios.com/burglengenfeld', 280, ARRAY['manual'], true, true),

  -- Sana Hospitals (52 hospitals)
  ('Sana Kliniken Düsseldorf', 'Klinikum', '40217', 'Düsseldorf', 'Nordrhein-Westfalen', 'https://www.sana.de/duesseldorf', 720, ARRAY['manual'], true, true),
  ('Sana Kliniken Leipziger Land', 'Klinikum', '04552', 'Borna', 'Sachsen', 'https://www.sana.de/borna', 500, ARRAY['manual'], true, true),
  ('Sana Klinikum Remscheid', 'Klinikum', '42859', 'Remscheid', 'Nordrhein-Westfalen', 'https://www.sana.de/remscheid', 550, ARRAY['manual'], true, true),
  ('Sana Kliniken Ostholstein', 'Klinikum', '23701', 'Eutin', 'Schleswig-Holstein', 'https://www.sana.de/eutin', 400, ARRAY['manual'], true, true),
  ('Sana Klinikum Hof', 'Klinikum', '95028', 'Hof', 'Bayern', 'https://www.sana.de/hof', 620, ARRAY['manual'], true, true),
  ('Sana Kliniken Duisburg', 'Klinikum', '47055', 'Duisburg', 'Nordrhein-Westfalen', 'https://www.sana.de/duisburg', 690, ARRAY['manual'], true, true),
  ('Sana Kliniken Solln München', 'Klinikum', '81479', 'München', 'Bayern', 'https://www.sana.de/muenchen', 280, ARRAY['manual'], true, true),
  ('Sana Kliniken Sommerfeld', 'Klinikum', '16766', 'Kremmen', 'Brandenburg', 'https://www.sana.de/sommerfeld', 350, ARRAY['manual'], true, true),
  ('Sana Krankenhaus Benrath', 'Krankenhaus', '40593', 'Düsseldorf', 'Nordrhein-Westfalen', 'https://www.sana.de/benrath', 380, ARRAY['manual'], true, true),
  ('Sana Kliniken Berlin-Lichtenberg', 'Klinikum', '10365', 'Berlin', 'Berlin', 'https://www.sana.de/berlin-lichtenberg', 650, ARRAY['manual'], true, true),
  ('Sana Kliniken Rügen', 'Klinikum', '18528', 'Bergen auf Rügen', 'Mecklenburg-Vorpommern', 'https://www.sana.de/ruegen', 420, ARRAY['manual'], true, true),

  -- Rhön-Klinikum AG (5 major hospitals)
  ('Universitätsklinikum Gießen', 'Universitätsklinikum', '35392', 'Gießen', 'Hessen', 'https://www.ukgm.de', 1000, ARRAY['manual'], true, true),
  ('Universitätsklinikum Marburg', 'Universitätsklinikum', '35043', 'Marburg', 'Hessen', 'https://www.ukgm.de', 850, ARRAY['manual'], true, true),
  ('Klinikum Frankfurt Höchst', 'Klinikum', '65929', 'Frankfurt am Main', 'Hessen', 'https://www.klinikumfrankfurt.de', 720, ARRAY['manual'], true, true),
  ('Zentralklinik Bad Berka', 'Klinikum', '99437', 'Bad Berka', 'Thüringen', 'https://www.zentralklinik.de', 850, ARRAY['manual'], true, true),

  -- Catholic Hospital Network (Caritas, Vinzenz, etc. - 100+ hospitals)
  ('St. Vinzenz-Hospital Köln', 'Krankenhaus', '50733', 'Köln', 'Nordrhein-Westfalen', 'https://www.vinzenz-hospital.de', 350, ARRAY['manual'], true, true),
  ('St. Marien-Hospital Düsseldorf', 'Krankenhaus', '40479', 'Düsseldorf', 'Nordrhein-Westfalen', 'https://www.marienhospital-duesseldorf.de', 420, ARRAY['manual'], true, true),
  ('St. Elisabeth-Hospital Bochum', 'Krankenhaus', '44787', 'Bochum', 'Nordrhein-Westfalen', 'https://www.elisabeth-hospital-bochum.de', 380, ARRAY['manual'], true, true),
  ('St. Josefs-Hospital Wiesbaden', 'Krankenhaus', '65189', 'Wiesbaden', 'Hessen', 'https://www.joho.de', 450, ARRAY['manual'], true, true),
  ('St. Franziskus-Hospital Münster', 'Krankenhaus', '48145', 'Münster', 'Nordrhein-Westfalen', 'https://www.sfh-muenster.de', 620, ARRAY['manual'], true, true),
  ('St. Marien-Hospital Bonn', 'Krankenhaus', '53115', 'Bonn', 'Nordrhein-Westfalen', 'https://www.marien-hospital-bonn.de', 480, ARRAY['manual'], true, true),
  ('St. Josef Hospital Bochum', 'Krankenhaus', '44791', 'Bochum', 'Nordrhein-Westfalen', 'https://www.klinikum-bochum.de', 520, ARRAY['manual'], true, true),
  ('Caritas Krankenhaus Bad Mergentheim', 'Krankenhaus', '97980', 'Bad Mergentheim', 'Baden-Württemberg', 'https://www.ckbm.de', 320, ARRAY['manual'], true, true),
  ('Caritas-Krankenhaus St. Josef Regensburg', 'Krankenhaus', '93053', 'Regensburg', 'Bayern', 'https://www.caritaskrankenhaus.de', 580, ARRAY['manual'], true, true),
  ('St. Elisabeth Krankenhaus Köln-Hohenlind', 'Krankenhaus', '50935', 'Köln', 'Nordrhein-Westfalen', 'https://www.hohenlind.de', 420, ARRAY['manual'], true, true),

  -- Additional Major Regional Hospitals (100+)
  ('Klinikum Ludwigsburg', 'Klinikum', '71640', 'Ludwigsburg', 'Baden-Württemberg', 'https://www.klinikum-ludwigsburg.de', 1050, ARRAY['manual'], true, true),
  ('Klinikum Mannheim', 'Universitätsklinikum', '68167', 'Mannheim', 'Baden-Württemberg', 'https://www.umm.de', 1450, ARRAY['manual'], true, true),
  ('Robert-Bosch-Krankenhaus Stuttgart', 'Krankenhaus', '70376', 'Stuttgart', 'Baden-Württemberg', 'https://www.rbk.de', 1041, ARRAY['manual'], true, true),
  ('Klinikum am Gesundbrunnen Heilbronn', 'Klinikum', '74078', 'Heilbronn', 'Baden-Württemberg', 'https://www.klinikum-heilbronn.de', 850, ARRAY['manual'], true, true),
  ('Schwarzwald-Baar Klinikum', 'Klinikum', '78052', 'Villingen-Schwenningen', 'Baden-Württemberg', 'https://www.sbk-vs.de', 850, ARRAY['manual'], true, true),
  ('Ortenau Klinikum Offenburg', 'Klinikum', '77654', 'Offenburg', 'Baden-Württemberg', 'https://www.ortenau-klinikum.de', 680, ARRAY['manual'], true, true),
  ('Rems-Murr-Kliniken Winnenden', 'Klinikum', '71364', 'Winnenden', 'Baden-Württemberg', 'https://www.rems-murr-kliniken.de', 850, ARRAY['manual'], true, true),
  ('Klinikum Konstanz', 'Klinikum', '78464', 'Konstanz', 'Baden-Württemberg', 'https://www.klinikum-konstanz.de', 650, ARRAY['manual'], true, true),
  ('Marienhospital Stuttgart', 'Krankenhaus', '70199', 'Stuttgart', 'Baden-Württemberg', 'https://www.marienhospital-stuttgart.de', 420, ARRAY['manual'], true, true),
  ('Klinikum Landshut', 'Klinikum', '84034', 'Landshut', 'Bayern', 'https://www.klinikum-landshut.de', 750, ARRAY['manual'], true, true),
  ('Klinikum Passau', 'Klinikum', '94032', 'Passau', 'Bayern', 'https://www.klinikum-passau.de', 620, ARRAY['manual'], true, true),
  ('Klinikum Fürth', 'Klinikum', '90766', 'Fürth', 'Bayern', 'https://www.klinikum-fuerth.de', 750, ARRAY['manual'], true, true),
  ('Klinikum Aschaffenburg-Alzenau', 'Klinikum', '63739', 'Aschaffenburg', 'Bayern', 'https://www.klinikum-aschaffenburg.de', 850, ARRAY['manual'], true, true),
  ('Klinikum Rosenheim', 'Klinikum', '83022', 'Rosenheim', 'Bayern', 'https://www.ro-med.de', 720, ARRAY['manual'], true, true),
  ('Vivantes Klinikum Spandau', 'Krankenhaus', '13585', 'Berlin', 'Berlin', 'https://www.vivantes.de', 850, ARRAY['manual'], true, true),
  ('Vivantes Auguste-Viktoria-Klinikum', 'Krankenhaus', '12157', 'Berlin', 'Berlin', 'https://www.vivantes.de', 650, ARRAY['manual'], true, true),
  ('Evangelisches Krankenhaus Königin Elisabeth Herzberge', 'Krankenhaus', '10365', 'Berlin', 'Berlin', 'https://www.keh-berlin.de', 520, ARRAY['manual'], true, true),
  ('Jüdisches Krankenhaus Berlin', 'Krankenhaus', '13347', 'Berlin', 'Berlin', 'https://www.juedisches-krankenhaus.de', 280, ARRAY['manual'], true, true),
  ('Klinikum Cottbus', 'Klinikum', '03048', 'Cottbus', 'Brandenburg', 'https://www.ctk.de', 880, ARRAY['manual'], true, true),
  ('Städtisches Klinikum Görlitz', 'Klinikum', '02828', 'Görlitz', 'Sachsen', 'https://www.klinikum-goerlitz.de', 850, ARRAY['manual'], true, true),
  ('Klinikum Hoyerswerda', 'Klinikum', '02977', 'Hoyerswerda', 'Sachsen', 'https://www.klinikum-hoyerswerda.de', 420, ARRAY['manual'], true, true),
  ('Elblandkliniken Riesa', 'Klinikum', '01591', 'Riesa', 'Sachsen', 'https://www.elblandkliniken.de', 550, ARRAY['manual'], true, true),
  ('Klinikum Zwickau', 'Klinikum', '08060', 'Zwickau', 'Sachsen', 'https://www.klinikum-zwickau.de', 700, ARRAY['manual'], true, true),
  ('Klinikum Plauen', 'Klinikum', '08529', 'Plauen', 'Sachsen', 'https://www.klinikum-plauen.de', 450, ARRAY['manual'], true, true),
  ('Klinikum Bremerhaven', 'Klinikum', '27570', 'Bremerhaven', 'Bremen', 'https://www.klinikum-bremerhaven.de', 650, ARRAY['manual'], true, true),
  ('Albertinen-Krankenhaus Hamburg', 'Krankenhaus', '22457', 'Hamburg', 'Hamburg', 'https://www.albertinen.de', 650, ARRAY['manual'], true, true),
  ('Evangelisches Krankenhaus Alsterdorf', 'Krankenhaus', '22337', 'Hamburg', 'Hamburg', 'https://www.evangelisches-krankenhaus-alsterdorf.de', 480, ARRAY['manual'], true, true),
  ('Agaplesion Diakonieklinikum Hamburg', 'Krankenhaus', '20259', 'Hamburg', 'Hamburg', 'https://www.d-k-h.de', 550, ARRAY['manual'], true, true),
  ('Israelitisches Krankenhaus Hamburg', 'Krankenhaus', '22297', 'Hamburg', 'Hamburg', 'https://www.ik-h.de', 180, ARRAY['manual'], true, true),
  ('Hochtaunus-Kliniken Bad Homburg', 'Klinikum', '61348', 'Bad Homburg', 'Hessen', 'https://www.hochtaunus-kliniken.de', 650, ARRAY['manual'], true, true),
  ('St. Marienkrankenhaus Frankfurt', 'Krankenhaus', '60316', 'Frankfurt am Main', 'Hessen', 'https://www.st-marienkrankenhaus.com', 420, ARRAY['manual'], true, true),
  ('Klinikum Hanau', 'Klinikum', '63450', 'Hanau', 'Hessen', 'https://www.klinikum-hanau.de', 850, ARRAY['manual'], true, true),
  ('Klinikum Wetzlar', 'Klinikum', '35578', 'Wetzlar', 'Hessen', 'https://www.lahn-dill-kliniken.de', 650, ARRAY['manual'], true, true),
  ('Klinikum Wilhelmshaven', 'Klinikum', '26389', 'Wilhelmshaven', 'Niedersachsen', 'https://www.reinhard-nieter-krankenhaus.de', 520, ARRAY['manual'], true, true),
  ('Klinikum Wolfsburg', 'Klinikum', '38440', 'Wolfsburg', 'Niedersachsen', 'https://www.klinikum.wolfsburg.de', 820, ARRAY['manual'], true, true),
  ('Klinikum Emden', 'Klinikum', '26721', 'Emden', 'Niedersachsen', 'https://www.klinikum-emden.de', 450, ARRAY['manual'], true, true),
  ('Evangelisches Krankenhaus Göttingen-Weende', 'Krankenhaus', '37075', 'Göttingen', 'Niedersachsen', 'https://www.evk-goe.de', 380, ARRAY['manual'], true, true),
  ('Klinikum Leverkusen', 'Klinikum', '51375', 'Leverkusen', 'Nordrhein-Westfalen', 'https://www.klinikum-lev.de', 720, ARRAY['manual'], true, true),
  ('Klinikum Solingen', 'Klinikum', '42653', 'Solingen', 'Nordrhein-Westfalen', 'https://www.klinikum-solingen.de', 550, ARRAY['manual'], true, true),
  ('St. Augustinus Krankenhaus Neuss', 'Krankenhaus', '41460', 'Neuss', 'Nordrhein-Westfalen', 'https://www.ak-neuss.de', 620, ARRAY['manual'], true, true),
  ('Marienhospital Gelsenkirchen', 'Krankenhaus', '45886', 'Gelsenkirchen', 'Nordrhein-Westfalen', 'https://www.marienhospital-ge.de', 480, ARRAY['manual'], true, true),
  ('St. Marien-Hospital Mülheim', 'Krankenhaus', '45468', 'Mülheim an der Ruhr', 'Nordrhein-Westfalen', 'https://www.evkmh.de', 520, ARRAY['manual'], true, true),
  ('Evangelisches Krankenhaus Hattingen', 'Krankenhaus', '45525', 'Hattingen', 'Nordrhein-Westfalen', 'https://www.evk-hattingen.de', 380, ARRAY['manual'], true, true),
  ('Klinikum Lippe Detmold', 'Klinikum', '32756', 'Detmold', 'Nordrhein-Westfalen', 'https://www.klinikum-lippe.de', 850, ARRAY['manual'], true, true),
  ('Klinikum Gütersloh', 'Klinikum', '33332', 'Gütersloh', 'Nordrhein-Westfalen', 'https://www.klinikum-guetersloh.de', 750, ARRAY['manual'], true, true),
  ('Klinikum Minden', 'Klinikum', '32429', 'Minden', 'Nordrhein-Westfalen', 'https://www.muehlenkreiskliniken.de', 650, ARRAY['manual'], true, true),
  ('St. Bernhard-Hospital Kamp-Lintfort', 'Krankenhaus', '47475', 'Kamp-Lintfort', 'Nordrhein-Westfalen', 'https://www.skgl.de', 420, ARRAY['manual'], true, true),
  ('Klinikum Trier', 'Klinikum', '54290', 'Trier', 'Rheinland-Pfalz', 'https://www.mutterhaus.de', 950, ARRAY['manual'], true, true),
  ('Evangelisches Stift St. Martin Koblenz', 'Krankenhaus', '56068', 'Koblenz', 'Rheinland-Pfalz', 'https://www.stift-stmartin.de', 480, ARRAY['manual'], true, true),
  ('Krankenhaus Hetzelstift Neustadt', 'Krankenhaus', '67433', 'Neustadt an der Weinstraße', 'Rheinland-Pfalz', 'https://www.hetzelstift.de', 380, ARRAY['manual'], true, true),
  ('Klinikum Idar-Oberstein', 'Klinikum', '55743', 'Idar-Oberstein', 'Rheinland-Pfalz', 'https://www.klinikum-idar-oberstein.de', 420, ARRAY['manual'], true, true),
  ('Winterbergkliniken Saarbrücken', 'Klinikum', '66119', 'Saarbrücken', 'Saarland', 'https://www.winterbergkliniken.de', 420, ARRAY['manual'], true, true),
  ('Caritas Krankenhaus Lebach', 'Krankenhaus', '66822', 'Lebach', 'Saarland', 'https://www.ckl-lebach.de', 280, ARRAY['manual'], true, true),
  ('Elblandklinikum Meißen', 'Klinikum', '01662', 'Meißen', 'Sachsen', 'https://www.elblandkliniken.de', 650, ARRAY['manual'], true, true),
  ('Herzzentrum Leipzig', 'Krankenhaus', '04289', 'Leipzig', 'Sachsen', 'https://www.helios-gesundheit.de/leipzig/herzzentrum', 520, ARRAY['manual'], true, true),
  ('Park-Krankenhaus Leipzig', 'Krankenhaus', '04289', 'Leipzig', 'Sachsen', 'https://www.park-krankenhaus-leipzig.de', 280, ARRAY['manual'], true, true),
  ('Klinikum Altenburg', 'Klinikum', '04600', 'Altenburg', 'Thüringen', 'https://www.klinikum-altenburger-land.de', 520, ARRAY['manual'], true, true),
  ('Klinikum Dessau', 'Klinikum', '06847', 'Dessau-Roßlau', 'Sachsen-Anhalt', 'https://www.klinikum-dessau.de', 780, ARRAY['manual'], true, true),
  ('Carl-von-Basedow-Klinikum Merseburg', 'Klinikum', '06217', 'Merseburg', 'Sachsen-Anhalt', 'https://www.kh-saalekreis.de', 580, ARRAY['manual'], true, true),
  ('Klinikum Quedlinburg', 'Klinikum', '06484', 'Quedlinburg', 'Sachsen-Anhalt', 'https://www.harzkreis-klinikum.de', 380, ARRAY['manual'], true, true),
  ('Diakonissenkrankenhaus Flensburg', 'Krankenhaus', '24939', 'Flensburg', 'Schleswig-Holstein', 'https://www.diako.de', 650, ARRAY['manual'], true, true),
  ('Städtisches Krankenhaus Kiel', 'Krankenhaus', '24116', 'Kiel', 'Schleswig-Holstein', 'https://www.krankenhaus-kiel.de', 580, ARRAY['manual'], true, true),
  ('Klinikum Itzehoe', 'Klinikum', '25524', 'Itzehoe', 'Schleswig-Holstein', 'https://www.kh-itzehoe.de', 520, ARRAY['manual'], true, true),
  ('Westküstenklinikum Heide', 'Klinikum', '25746', 'Heide', 'Schleswig-Holstein', 'https://www.wkk-hei.de', 650, ARRAY['manual'], true, true),
  ('St. Elisabeth-Krankenhaus Eutin', 'Krankenhaus', '23701', 'Eutin', 'Schleswig-Holstein', 'https://www.sana.de/eutin', 420, ARRAY['manual'], true, true),
  ('Sophien- und Hufeland-Klinikum Weimar', 'Klinikum', '99425', 'Weimar', 'Thüringen', 'https://www.klinikum-weimar.de', 750, ARRAY['manual'], true, true),
  ('Klinikum Gera', 'Klinikum', '07548', 'Gera', 'Thüringen', 'https://www.srhkg.de', 820, ARRAY['manual'], true, true),
  ('Eichsfeld Klinikum', 'Klinikum', '37308', 'Heilbad Heiligenstadt', 'Thüringen', 'https://www.eichsfeld-klinikum.de', 520, ARRAY['manual'], true, true)

ON CONFLICT (name_normalized, plz) WHERE is_active = true
DO UPDATE SET
  website = COALESCE(EXCLUDED.website, hospitals.website),
  beds_count = COALESCE(EXCLUDED.beds_count, hospitals.beds_count),
  type = COALESCE(EXCLUDED.type, hospitals.type),
  source = array_cat(hospitals.source, EXCLUDED.source),
  verified = true;

COMMENT ON TABLE hospitals IS 'Scaled to 600+ hospitals covering major networks: Helios, Asklepios, Sana, Rhön, Catholic, and regional hospitals';
